{{- if contains "sqlite" .Values.linkstack.backend }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ include "linkstack.fullname" . }}-sqlite-pvc'
  labels:
    {{- include "linkstack.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
{{- end }}
