repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.33.0"
    hooks:
      - id: "yamllint"
        args:
          - "-c=.yamllint.yaml"
          - "-s"
