repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.33.0"
    hooks:
      - id: "yamllint"
        args:
          - "-c=.yamllint.yaml"
          - "-s"
  # This hook compliments the yamllint (as Helm templates are not valid YAML files).
  - repo: "https://github.com/gruntwork-io/pre-commit"
    rev: "v0.1.23"  # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      - id: "helmlint"
