repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.33.0"
    hooks:
      - id: "yamllint"
        args:
          - "-c=.yamllint.yaml"
          - "-s"
  # This hook compliments the yamllint (as Helm templates are not valid YAML files).
  - repo: "https://github.com/gruntwork-io/pre-commit"
    rev: "v0.1.23"  # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      - id: "helmlint"
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.11.3
    hooks:
      - id: helm-docs
        args:
          # Make the tool search for charts only under the `example-charts` directory
          - --chart-search-root=./

          # Repeating the flag adds this to the list, now [./_templates.gotmpl, README.md.gotmpl]
          # A base filename makes it relative to each chart directory found
          - --template-files=./README.md.gotmpl
  - repo: https://github.com/norwoodj/helm-docs
    rev: ""
    hooks:
      - id: helm-docs
        args:
          # Make the tool search for charts only under the `charts` directory
          - --chart-search-root=.
          - --template-files=./README.md.gotmpl
