apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "linkstack.fullname" . }}
  {{- if ne .Values.namespace "" }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    {{- include "linkstack.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "linkstack.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "linkstack.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "linkstack.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- if not .Values.objectStorageBackup.enabled }} # files will be copied from Docker image
        - name: cp
          image: "{{ .Values.linkstack.image.repository }}:{{ .Values.linkstack.image.tag | default .Chart.AppVersion }}"
          resources:
            {{- toYaml .Values.linkstack.resources | nindent 12 }}
          command: ["/bin/ash", "-c", "sleep 1 && \
          [ -z \"$(ls -A /htdocs_provisioning)\" ] && \
          cp -Ra /htdocs/. /htdocs_provisioning/ && \
          chown -R apache:apache /htdocs_provisioning && \
          find /htdocs -type d -print0 | xargs -0 chmod 0755 && \
          find /htdocs -type f -print0 | xargs -0 chmod 0644 && \
          echo \"/htdocs was empty. Files copied to /htdocs.\" || \
          echo \"/htdocs is not empty. No files copied.\""]
          volumeMounts:
            - name: linkstack-sqlite
              mountPath: /htdocs_provisioning
        {{- else }} # files will be copied from remote backup storage
        - name: restore-storage
          image: "rclone/rclone"
          imagePullPolicy: IfNotPresent
          resources:
            {{- toYaml .Values.linkstack.resources | nindent 12 }}
          command: ["sh", "-c", "rclone sync \
            {{ .Values.objectStorageBackup.rcloneBucketPath }} /htdocs \
            --s3-access-key-id=${RCLONE_CONFIG_S3_ACCESS_KEY_ID} \
            --s3-secret-access-key=${RCLONE_CONFIG_S3_SECRET_ACCESS_KEY} \
            --s3-region={{ .Values.objectStorageBackup.rcloneBucketRegion }} \
            --transfers 15 \
            --checkers 30 \
            --use-json-log \
            --s3-env-auth=true \
            --s3-provider={{ .Values.objectStorageBackup.rcloneBucketProvider }} \
            --no-check-certificate \
            --ignore-checksum"
          ]
          env:
          - name: RCLONE_CONFIG_S3_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: rclone
                key: AWS_ACCESS_KEY_ID
          - name: RCLONE_CONFIG_S3_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: rclone
                key: AWS_SECRET_ACCESS_KEY
          - name: RCLONE_CONFIG_S3_TYPE
            value: s3
          {{- with .Values.linkstack.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: restore-permissions # required since rclone doesn't handle permissions at all
          image: "linkstackorg/linkstack"
          resources:
            {{- toYaml .Values.linkstack.resources | nindent 12 }}
          command: ["/bin/ash", "-c", "sleep 1 && \
          chown -R apache:apache /htdocs && \
          find /htdocs -type d -print0 | xargs -0 chmod 0755 && \
          find /htdocs -type f -print0 | xargs -0 chmod 0644 && \
          echo \"/Permissions restored on /htdocs.\""]
          volumeMounts:
            - name: linkstack-sqlite
              mountPath: /htdocs
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.linkstack.image.repository }}:{{ .Values.linkstack.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.linkstack.image.pullPolicy }}
          {{- with .Values.litestream.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
              httpHeaders:
              - name: User-Agent
                value: LivenessProbe
            initialDelaySeconds: 1
            periodSeconds: 5
            failureThreshold: 2
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
              httpHeaders:
              - name: User-Agent
                value: ReadinessProbe
            initialDelaySeconds: 1
            periodSeconds: 5
            failureThreshold: 2
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.linkstack.resources | nindent 12 }}
          {{- with .Values.linkstack.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
