apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "linkstack.fullname" . }}
  {{- if ne .Values.namespace "" }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    {{- include "linkstack.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "linkstack.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "linkstack.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "linkstack.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: cp
          image: "{{ .Values.linkstack.image.repository }}:{{ .Values.linkstack.image.tag | default .Chart.AppVersion }}"
          resources:
            {{- toYaml .Values.linkstack.resources | nindent 12 }}
          command: ["/bin/ash", "-c", "sleep 1 && \
          cp -Ra /htdocs/. /htdocs_provisioning/ && \
          chown -R apache:apache /htdocs_provisioning && \
          find /htdocs -type d -print0 | xargs -0 chmod 0755 && \
          find /htdocs -type f -print0 | xargs -0 chmod 0644"]
          volumeMounts:
            - name: linkstack-sqlite
              mountPath: /htdocs_provisioning
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.linkstack.image.repository }}:{{ .Values.linkstack.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.linkstack.image.pullPolicy }}
          env:
          {{- range $key, $value := .Values.linkstack.env }}
          - name: {{ $key | upper | replace "." "_" }}
            value: {{ $value | quote }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.linkstack.resources | nindent 12 }}
          {{- with .Values.linkstack.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- if contains "sqlite" .Values.linkstack.backend }}
        - name: litestream
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.litestream.image.repository }}:{{ .Values.litestream.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.litestream.pullPolicy }}
          resources:
            {{- toYaml .Values.litestream.resources | nindent 12 }}
          args: ["replicate"]
          env:
          - name: LITESTREAM_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: litestream
                key: LITESTREAM_ACCESS_KEY_ID
          - name: LITESTREAM_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: litestream
                key: LITESTREAM_SECRET_ACCESS_KEY
          {{- with .Values.litestream.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
