{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "linkstack.fullname" . }}
  {{- if ne .Values.namespace "" }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    {{- include "linkstack.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: linkstack
  policyTypes:
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
      {{- with .Values.networkPolicy.ports }}
      ports:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  egress: []
{{- end }}
